---

# -------------------------------------------------------------------------------------------------
# Job Name
# -------------------------------------------------------------------------------------------------
name: lint


# -------------------------------------------------------------------------------------------------
# When to run
# -------------------------------------------------------------------------------------------------
on:
  # Runs on Pull Requests
  pull_request:


# -------------------------------------------------------------------------------------------------
# What to run
# -------------------------------------------------------------------------------------------------
jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        target:
          - lint
          - gen

    steps:
      # ------------------------------------------------------------
      # Setup repository
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # ------------------------------------------------------------
      # Lint repository
      # ------------------------------------------------------------
      - name: "make ${{ matrix.target }}"
        run: |
          retry() {
            for n in $(seq ${RETRIES}); do
              echo "[${n}/${RETRIES}] ${*}";
              if eval "${*}"; then
                echo "[SUCC] ${n}/${RETRIES}";
                return 0;
              fi;
              sleep 2;
              echo "[FAIL] ${n}/${RETRIES}";
            done;
            return 1;
          }

          retry make "${TARGET}"
          git diff --quiet || { echo "Build Changes"; git diff; git status; false; }
        env:
          TARGET: ${{ matrix.target }}
          RETRIES: 20
